### ISSUE TITLE
Workplan

### ISSUE THREAD

**Issue by elParaguayo** [elParaguayo/pi-radio#1]
Master schedule of things to do...

_**Pre-script items**_
- [ ] Get bluetooth working on Pi
- [ ] Get Airplay working
- [ ] Get squeezelite working
- [ ] Get internet radio working

_**Script items**_
- [ ] Get rotary encoders working
- [ ] LEDs for services
- [ ] LCD display module
- [ ] Menu system
- [ ] ... more stuff which will become obvious as this progresses
- [ ] Create systemd service

_**Post-script items**_
- [ ] Design physical layout for laser cutting
